apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpecBinding
metadata:
  name: accountmgr-binding
  namespace: default
spec:
  services:
  - name: accountmgr
    namespace: default
  api_specs:
  - name: accountmgr-api
    namespace: default
